spring:
  freemarker:
    template-loader-path: classpath:/templates,classpath:/static
    suffix: .ftl
  datasource:
    driver-class-name: org.postgresql.Driver
    username: dogeshop
    password: pass112311
    url: jdbc:postgresql://localhost:5432/dogeshop
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  messages:
    basename: languages.messages
server:
  port: 8080
